services:
  whatsapp-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/sessions:/app/backend/sessions
    restart: always
    environment:
      - NODE_ENV=production
      - CHROME_PATH=/usr/bin/chromium
