#!/usr/bin/env bash
# WA Reach — first deploy onto a bare Ubuntu VPS.
#
#   ssh root@<your-vps>
#   curl -fsSL https://raw.githubusercontent.com/audumber3000/whatsapp-cloud/feat/evolution-api/ops/deploy-vps.sh | bash
#
# Safe to re-run: secrets already in .env.prod are kept, migrations are
# idempotent, and compose reconciles rather than rebuilding from scratch.
set -euo pipefail

REPO="https://github.com/audumber3000/whatsapp-cloud.git"
BRANCH="feat/evolution-api"
APP_DIR="/opt/wareach"
ENV_FILE="$APP_DIR/.env.prod"
COMPOSE="docker compose -f docker-compose.prod.yml --env-file .env.prod"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run this as root"

# ── 1. Docker ───────────────────────────────────────────────────────────────
if command -v docker >/dev/null 2>&1; then
    log "Docker already installed ($(docker --version))"
else
    log "Installing Docker"
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl git >/dev/null
    curl -fsSL https://get.docker.com | sh >/dev/null
    systemctl enable --now docker
fi
docker compose version >/dev/null 2>&1 || die "the docker compose plugin is missing"

# ── 2. Swap ─────────────────────────────────────────────────────────────────
# 4 GB across Node + Evolution + Postgres + Redis has little headroom, and the
# OOM killer takes the app before it takes the database.
if [ "$(swapon --show --noheadings | wc -l)" -eq 0 ]; then
    log "Adding 2G swap (none present)"
    fallocate -l 2G /swapfile
    chmod 600 /swapfile
    mkswap /swapfile >/dev/null
    swapon /swapfile
    grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
else
    log "Swap already configured"
fi

# ── 3. Source ───────────────────────────────────────────────────────────────
if [ -d "$APP_DIR/.git" ]; then
    log "Updating existing checkout at $APP_DIR"
    git -C "$APP_DIR" fetch --quiet origin "$BRANCH"
    git -C "$APP_DIR" checkout --quiet "$BRANCH"
    git -C "$APP_DIR" reset --hard --quiet "origin/$BRANCH"
else
    log "Cloning $BRANCH into $APP_DIR"
    git clone --quiet --branch "$BRANCH" "$REPO" "$APP_DIR"
fi
cd "$APP_DIR"
echo "    at commit $(git rev-parse --short HEAD)"

# ── 4. Secrets ──────────────────────────────────────────────────────────────
PUBLIC_IP="$(curl -fsS --max-time 10 https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')"

if [ -f "$ENV_FILE" ]; then
    log "Keeping the existing .env.prod (delete it to regenerate secrets)"
else
    log "Generating .env.prod — random secrets, email left blank for you"
    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by ops/deploy-vps.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Secrets below are random and unique to this box. Keep this file off git.

WAREACH_PUBLIC_URL=http://${PUBLIC_IP}:3000
SERVER_URL=http://evolution:8080
CORS_ORIGINS=

JWT_SECRET=$(openssl rand -hex 32)
JWT_EXPIRES_IN=12h
AUTHENTICATION_API_KEY=$(openssl rand -hex 32)
EVOLUTION_WEBHOOK_SECRET=$(openssl rand -hex 32)
WAREACH_WEBHOOK_SECRET=$(openssl rand -hex 32)

POSTGRES_PASSWORD=$(openssl rand -hex 24)
WAREACH_DB_PASSWORD=$(openssl rand -hex 24)

ADMIN_USERNAME=admin
ADMIN_PASSWORD_HASH=

# Fill these in for password reset, failure alerts and daily summaries,
# then: docker compose -f docker-compose.prod.yml --env-file .env.prod up -d
EMAIL_HOST=
EMAIL_PORT=587
EMAIL_USER=
EMAIL_PASS=
EMAIL_FROM=

MOLARPLUS_URL=
EOF
    chmod 600 "$ENV_FILE"
fi

# ── 5. Build ────────────────────────────────────────────────────────────────
log "Building the application image (a few minutes on first run)"
$COMPOSE build wareach

# ── 6. Admin password ───────────────────────────────────────────────────────
# Hashed with the same bcrypt build the app verifies against, so there is no
# chance of a $2y$/$2b$ mismatch between generator and verifier.
if grep -q '^ADMIN_PASSWORD_HASH=$' "$ENV_FILE"; then
    log "Set the master admin password"
    echo "    (leave blank to skip — the admin panel stays disabled)"
    read -rsp "    Password: " ADMIN_PW; echo
    if [ -n "$ADMIN_PW" ]; then
        HASH="$(ADMIN_PW="$ADMIN_PW" $COMPOSE run --rm --no-deps -T \
            -e ADMIN_PW wareach \
            node -e 'process.stdout.write(require("bcrypt").hashSync(process.env.ADMIN_PW,10))' \
            2>/dev/null | tr -d '\r\n')"
        case "$HASH" in
            \$2*) sed -i "s|^ADMIN_PASSWORD_HASH=$|ADMIN_PASSWORD_HASH=${HASH}|" "$ENV_FILE"
                  echo "    hash written to .env.prod" ;;
            *)    echo "    could not generate a hash — set ADMIN_PASSWORD_HASH by hand" ;;
        esac
    fi
fi

# ── 7. Up ───────────────────────────────────────────────────────────────────
log "Starting the stack"
$COMPOSE up -d

log "Waiting for the app to become healthy"
for i in $(seq 1 60); do
    if curl -fsS --max-time 3 http://localhost:3000/api/health >/dev/null 2>&1; then
        echo "    healthy after ${i}s"
        break
    fi
    [ "$i" -eq 60 ] && {
        echo "    still not healthy — recent logs:"
        $COMPOSE logs --tail 40 wareach
        die "the app did not come up"
    }
    sleep 1
done

# ── 8. Firewall ─────────────────────────────────────────────────────────────
if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q '^Status: active'; then
    log "Opening port 3000 in ufw"
    ufw allow 3000/tcp >/dev/null
fi

# ── 9. Report ───────────────────────────────────────────────────────────────
log "Done"
echo
echo "    Live at:  http://${PUBLIC_IP}:3000"
echo "    Health:   $(curl -fsS --max-time 5 http://localhost:3000/api/health)"
echo
echo "    Running:"
$COMPOSE ps --format '      {{.Service}}\t{{.Status}}' 2>/dev/null || $COMPOSE ps
echo
echo "    Next:"
echo "      - sign up at the URL above, then link WhatsApp by scanning the QR"
echo "      - fill EMAIL_* in $ENV_FILE for alerts and password reset"
echo "      - this is plain HTTP on a bare IP; put a domain and TLS in front"
echo "        before real patient data goes through it"
echo
